---
- name: Create Node-RED group
  group:
    name: "{{ nodered_user }}"
    state: present
- name: Create Node-RED user
  user:
    name: "{{ nodered_user }}"
    group: "{{ nodered_user }}"
    groups: "dialout"
    append: yes

- name: Check if Node-RED is already installed
  stat:
    path: "/usr/bin/node-red-pi"
  register: nodered_bin

- name: Check if nodered user is allowed to sudo without password
  command: "sudo -n true"
  become: yes
  become_user: "{{ nodered_user }}"
  register: nodered_sudo
  changed_when: "nodered_sudo.rc != 0"
  failed_when: "'FAILED' in nodered_sudo.stderr"
  when: nodered_bin.stat.exists == false or nodered_force_install

- name: Allow nodered user sudo without password for Node-RED installer
  lineinfile:
    dest: /etc/sudoers.d/099_ansible-nopasswd-tmp
    state: present
    create: yes
    regexp: "^{{ nodered_user }}"
    line: "{{ nodered_user }} ALL=(ALL) NOPASSWD: ALL"
    validate: "visudo -cf %s"
  when: (nodered_bin.stat.exists == false or nodered_force_install) and nodered_sudo.rc != 0

- name: Install current node.js and Node-RED
  shell: "yes | bash <(curl -sL https://raw.githubusercontent.com/node-red/raspbian-deb-package/master/resources/update-nodejs-and-nodered)"
  args:
    chdir: "{{ nodered_home }}"
    executable: "/bin/bash"
  become: yes
  become_user: "{{ nodered_user }}"
  when: nodered_bin.stat.exists == false or nodered_force_install

- name: Remove temporary sudo permissions again
  file:
    path: /etc/sudoers.d/099_ansible-nopasswd-tmp
    state: absent

- name: Enable Node-RED service
  systemd:
    daemon_reload: yes
    name: nodered
    enabled: yes
    state: started

- name: Wait for initial Node-RED start
  wait_for:
    path: "{{ nodered_dir }}"


- name: Install Node-RED extra nodes
  shell: "npm install {{ item }}"
  args:
    chdir: "{{ nodered_dir }}"
    creates: "{{ nodered_dir }}/node_modules/{{ item }}"
  become: yes
  become_user: "{{ nodered_user }}"
  with_items:
    - node-red-node-sqlite
    - node-red-contrib-telegrambot
    - node-red-dashboard


- name: Install Node-RED neopixel
  include: nodered-neopixel.yml
  when: nodered_neopixel
