---
rpi_wifi_client: false
rpi_serial: false
rpi_power: true
rpi_mosquitto: true

rpi_nodered: false
rpi_nodered_user: "nodered"
rpi_nodered_home: "/home/{{ rpi_nodered_user }}"
rpi_nodered_dir: "{{ rpi_nodered_home }}/.node-red"
rpi_nodered_force_install: false
rpi_nodered_neopixel: false
